# ============================================================================
# AgentCore Unity — Meta File Integrity Verifier
# ============================================================================
# Purpose:
#   Scan every .cs / .uxml / .uss / .asmdef / .md.template / .md file under
#   Editor/ and confirm each has a sibling .meta file. Unity's UPM read-only
#   package model REQUIRES .meta files: assets without .meta in a read-only
#   package are silently NOT compiled into their target asmdef.
#
# Historical context:
#   v1.4.5 shipped OptionalComponentDefaultsBootstrap.cs without its .meta,
#   causing the [InitializeOnLoadMethod] to never run and VCS auto-enable to
#   fail on every fresh install. This script exists to make that class of bug
#   impossible to ship again.
#
# Usage:
#   powershell -File tools/verify-meta.ps1
#   powershell -File tools/verify-meta.ps1 -Fix   # NOT implemented — meta must
#                                                  # be generated by Unity to
#                                                  # get valid GUIDs
#
# Exit codes:
#   0  All assets have corresponding .meta files
#   1  One or more assets are missing .meta (details printed to stderr)
#   2  Script argument / environment error
# ============================================================================

[CmdletBinding()]
param(
    [string]$Root = "Editor",
    [string[]]$Extensions = @('.cs', '.uxml', '.uss', '.asmdef', '.md', '.template', '.json', '.txt'),
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Root -PathType Container)) {
    Write-Error "Root directory not found: $Root"
    exit 2
}

# Collect all candidate files (excluding .meta itself).
# Also skip files whose extension we don't consider Unity assets.
$candidates = Get-ChildItem -Path $Root -Recurse -File `
    | Where-Object {
        $_.Name -notlike '*.meta' -and
        ($Extensions -contains $_.Extension -or $_.Name -like '*.md.template')
      }

# Every Unity-visible file (.cs, .uxml, .uss, .asmdef, .md, .template, etc.)
# MUST have a sibling .meta file OR Unity will complain and — in read-only
# UPM packages — silently exclude it from compilation.
$missing = @()
foreach ($f in $candidates) {
    $metaPath = "$($f.FullName).meta"
    if (-not (Test-Path -LiteralPath $metaPath -PathType Leaf)) {
        $missing += $f.FullName
    }
}

# Also verify: every directory under Editor/ should have a .meta (Unity
# requires directory meta for asmdef nesting to work correctly).
$dirCandidates = Get-ChildItem -Path $Root -Recurse -Directory
$dirMissing = @()
foreach ($d in $dirCandidates) {
    $metaPath = "$($d.FullName).meta"
    if (-not (Test-Path -LiteralPath $metaPath -PathType Leaf)) {
        $dirMissing += $d.FullName
    }
}

$totalMissing = $missing.Count + $dirMissing.Count

if ($totalMissing -eq 0) {
    if (-not $Quiet) {
        $fileCount = ($candidates | Measure-Object).Count
        $dirCount = ($dirCandidates | Measure-Object).Count
        Write-Host "[verify-meta] OK — $fileCount files + $dirCount dirs under '$Root' all have .meta" -ForegroundColor Green
    }
    exit 0
}

Write-Host ""
Write-Host "[verify-meta] FAIL — $totalMissing asset(s) missing .meta file(s):" -ForegroundColor Red
Write-Host ""

if ($missing.Count -gt 0) {
    Write-Host "  Files without .meta:" -ForegroundColor Yellow
    foreach ($m in $missing) {
        # Print path relative to workspace for cleaner output.
        $rel = Resolve-Path -LiteralPath $m -Relative
        Write-Host "    - $rel" -ForegroundColor Red
    }
    Write-Host ""
}

if ($dirMissing.Count -gt 0) {
    Write-Host "  Directories without .meta:" -ForegroundColor Yellow
    foreach ($m in $dirMissing) {
        $rel = Resolve-Path -LiteralPath $m -Relative
        Write-Host "    - $rel" -ForegroundColor Red
    }
    Write-Host ""
}

Write-Host "How to fix:" -ForegroundColor Cyan
Write-Host "  1. Open the workspace in Unity (Editor auto-generates missing .meta on import)" -ForegroundColor Cyan
Write-Host "  2. Verify the generated .meta is committed to the repo" -ForegroundColor Cyan
Write-Host "  3. Re-run: powershell -File tools/verify-meta.ps1" -ForegroundColor Cyan
Write-Host ""
Write-Host "DO NOT hand-write .meta files — Unity relies on stable GUIDs generated on import." -ForegroundColor Yellow
Write-Host ""

exit 1
